version: '3'
services:
  web:
    build:
      context: ./web
      dockerfile: dev.Dockerfile
    ports:
      - "8080:8080"
      - "28080:28080"
    volumes:
      - ./web/:/usr/src/app/
      
  pg:
    volumes:
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data:
    driver: local